#!/usr/bin/env python
from __future__ import division
import time

# Import the PCA9685 module.
import Adafruit_PCA9685
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)

# power-up servo controller
GPIO.setup(18, GPIO.OUT)
GPIO.output(18, 0)
time.sleep(.5)

# Initialise the PCA9685 using the default address (0x40).
pwm = Adafruit_PCA9685.PCA9685()

# Configure min and max servo pulse lengths (450 total, 25 corresponds to 10 degrees)
servo_min = 225  # Min pulse length out of 4096
servo_max = 725  # Max pulse length out of 4096

with open('/etc/motioneye/vert_pos', 'r') as f:
    vert_pos = int(f.readline())
    print vert_pos
    f.close()

# Set frequency to 60hz, good for servos.
pwm.set_pwm_freq(60)

if ( vert_pos != servo_max ):
        vert_pos += 25
        pwm.set_pwm(0, 0, vert_pos)
        with open('/etc/motioneye/vert_pos', 'w') as f:
            f.write(str(vert_pos))
            f.close()

# power-up servo controller
time.sleep(.5)
GPIO.output(18, 1)

raise SystemExit
